### ISSUE TITLE
Что означает эта конструкция?

### ISSUE THREAD

**Issue by DanaZL** [as83davydov/learn-homework-1#1]
https://github.com/as83davydov/learn-homework-1/blob/595a911964f660f295edbea1dce1a7512d2b0f25/1_if1.py#L38

Кажется __main__ не стоило менять, это выражение языка, которое не зависит от функций которые мы вызываем

**Comment by as83davydov** [comment]
Да, так и есть, поменял от незнания. Теперь исправил
